obj-m += que2.o

all:
	make -C /lib/modules/6.14.0-35-generic/build M=/home/desd-user04/Desktop/DD_7/param modules

clean:
	make -C /lib/modules/6.14.0-35-generic/build M=/home/desd-user04/Desktop/DD_7/param clean
